[package]
name = "tiphys-tui"
description = "The Tiphys terminal app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
tiphys-core.workspace = true
ratatui.workspace = true
crossterm.workspace = true
unicode-width.workspace = true
tokio.workspace = true
